MyFirstBlog/Models/DailyPost.cs
namespace MyFirstBlog.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("DailyPost")]
    public partial class DailyPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DailyPost()
        {
            imageDailyPosts = new HashSet<imageDailyPost>();
            imageDailyPosts1 = new HashSet<imageDailyPost>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int postID { get; set; }

        [Required]
        [StringLength(100)]
        public string postTitle { get; set; }

        [Column(TypeName = "ntext")]
        [Required]
        public string postContent { get; set; }

        [Column(TypeName = "date")]
        public DateTime dateWrite { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imageDailyPost> imageDailyPosts { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imageDailyPost> imageDailyPosts1 { get; set; }
    }
}

MyFirstBlog/Models/Trip.cs
namespace MyFirstBlog.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Trip
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int postID { get; set; }

        public int? userID { get; set; }

        [StringLength(200)]
        public string postTitle { get; set; }

        [StringLength(500)]
        public string postSummary { get; set; }

        [Column(TypeName = "date")]
        public DateTime? date { get; set; }

        [Column(TypeName = "ntext")]
        public string postContent { get; set; }

        [StringLength(300)]
        public string friends { get; set; }

        public string imgThumbnail { get; set; }

        public string imageFolder { get; set; }
    }
}

MyFirstBlog/Models/user.cs
namespace MyFirstBlog.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("user")]
    public partial class user
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int userID { get; set; }

        [StringLength(20)]
        public string username { get; set; }

        [StringLength(18)]
        public string password { get; set; }

        public int? role_id { get; set; }

        [StringLength(100)]
        public string useremail { get; set; }

        public virtual userInfo userInfo { get; set; }

        public virtual userRole userRole { get; set; }
    }
}

MyFirstBlog/Controllers/DailyPostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyFirstBlog.Models;
using PagedList;
namespace MyFirstBlog.Controllers
{
    public class DailyPostController : Controller
    {
        //
        // GET: /DailyPost/
        private MyBlogDBModel data = new MyBlogDBModel();
        public ActionResult Index()
        {
            return View(data.DailyPosts.OrderByDescending(p => p.dateWrite));
        }
        [HttpPost]
        public ActionResult Index(string sortType)
        {
            string type = Request.Form["order-type"].ToString();
            var posts = data.DailyPosts.AsQueryable();
            ViewBag.selected = "Des";
            if (type == "Inscrease")
            {
                posts = data.DailyPosts.OrderByDescending(p => p.dateWrite);
                ViewBag.selected = "Ins";
            }
            else posts = data.DailyPosts;
            return View(posts);
        }
        public ActionResult Post(int id)
        {
            return View(data.DailyPosts.Where(p => p.postID == id).FirstOrDefault());
        }
        [HttpGet]
        [MyFirstBlog.Common.CustomAthorize(Roles ="superadmin")]
        public ActionResult WritePost()
        {
            ViewBag.OK = TempData["writepost"];
            return View();
        }
        [HttpPost,ValidateInput(false)]
        public ActionResult WritePost(FormCollection form)
        {
            if ((string.IsNullOrEmpty(form["title"]) || (string.IsNullOrEmpty(form["content"])) || (string.IsNullOrEmpty(form["date"]))))
            {
                TempData["writepost"] = "Input is invalid";
            }
            else
            {
                DailyPost newpost = new DailyPost();
                newpost.postID = data.DailyPosts.Count() + 1;
                newpost.postTitle = form["title"];
                newpost.postContent = form["content"].ToString();
                newpost.dateWrite = DateTime.Parse(form["date"]);
                data.DailyPosts.Add(newpost);
                data.SaveChanges();
                TempData["writepost"] = "Successfully Posted";
            }
            return RedirectToAction("WritePost");
        }
        [MyFirstBlog.Common.CustomAthorize(Roles = "superadmin")]
        public ActionResult EditPost(int id)
        {
            ViewBag.OK = TempData["editpost"];
            return View(data.DailyPosts.Where(p => p.postID == id).FirstOrDefault());
        }
        [HttpPost]
        [MyFirstBlog.Common.CustomAthorize(Roles = "superadmin")]
        public ActionResult EditPost(FormCollection form)
        {
            DailyPost newpost = new DailyPost();
            newpost.postID = Convert.ToInt32(form["postid"]);
            newpost.postTitle = form["title"];
            newpost.postContent = form["content"].ToString();
            newpost.dateWrite = DateTime.Parse(form["date"]);
            DailyPost p = data.DailyPosts.Where(post => post.postID == newpost.postID).FirstOrDefault();
            p.dateWrite = newpost.dateWrite;
            p.postContent = newpost.postContent;
            p.postTitle = newpost.postTitle;
            data.SaveChanges();
            TempData["editpost"] = "Successfully Edited";
            return RedirectToAction("EditPost", new { id = p.postID });
        }
        [HttpPost]
        [MyFirstBlog.Common.CustomAthorize(Roles = "superadmin")]
        public string DeletePost(string id)
        {
            int idpost = Convert.ToInt32(id);
            DailyPost p = data.DailyPosts.Where(post => post.postID == idpost).FirstOrDefault();
            data.DailyPosts.Remove(p);
            data.SaveChanges();
            return "succeed";
        }
    }
}

MyFirstBlog/Controllers/FriendsandMeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyFirstBlog.Models;
using PagedList;

namespace MyFirstBlog.Controllers
{
    public class FriendsandMeController : Controller
    {
        //
        // GET: /FriendsandMe/
        private MyBlogDBModel data = new MyBlogDBModel();
        public ActionResult Trips()
        {
            ViewBag.lastests = data.Trips.OrderByDescending(p => p.date).Take(4);
            return View(data.Trips.OrderByDescending(p => p.date));
        }      
        public ActionResult Trip(int id)
        {
            var trip = data.Trips.Where(t => t.postID == id).FirstOrDefault();
            ViewBag.others = data.Trips.OrderByDescending(p=>p.date).Take(5);
            return View(trip);
        }
        public ActionResult PreviewTrip(int id)
        {
            var trip = data.previewTrips.Where(t => t.previewID == id).FirstOrDefault();
            return View(trip);
        }
       [MyFirstBlog.Common.CustomAthorize(Roles = "superadmin,admin,friends")]
        [HttpPost]
        public ActionResult WriteTrip()
        {
            return View();
        }
        [MyFirstBlog.Common.CustomAthorize(Roles = "superadmin,admin,friends")]
       [HttpPost,ValidateInput(false)]
       public ActionResult WriteTriped(FormCollection form)
        {
            if (!(String.IsNullOrEmpty(form["title"])) && !(String.IsNullOrEmpty(form["content"])) && (!String.IsNullOrEmpty(form["summary"])) && (!String.IsNullOrEmpty(form["thumbnail"])))
            {
                previewTrip newtrip = new previewTrip();
                var total=data.previewTrips.Count();
                if (total == 0)
                {
                    newtrip.previewID = 0;
                }
                else
                {
                    newtrip.previewID = data.previewTrips.OrderByDescending(p => p.previewID).FirstOrDefault().previewID + 1;
                }
                newtrip.postID = data.Trips.OrderByDescending(p => p.postID).FirstOrDefault().postID + 1;
                newtrip.date = DateTime.Now;
                newtrip.userID = ((user)Session["current_user"]).userID;
                newtrip.postTitle = form["title"];
                newtrip.postContent = form["content"];
                newtrip.postSummary = form["summary"];
                newtrip.imgThumbnail = form["thumbnail"];
                if (!String.IsNullOrEmpty(form["folder"]))
                {
                    newtrip.imageFolder = form["folder"];
                }
                data.previewTrips.Add(newtrip);
                data.SaveChanges();
                return Redirect("http://dangduoc.azurewebsites.net/FriendsandMe/PreviewTrip?id=" + newtrip.previewID);
            }
            else
                return View("Error");
        }
        [MyFirstBlog.Common.CustomAthorize(Roles = "superadmin,admin,friends")]
        [HttpGet]
        public ActionResult EditTrip(int id)
        {
            user crnt_user = (user)Session["current_user"];
            var trip = data.Trips.Where(t => t.postID == id).FirstOrDefault();
            if (crnt_user.userID != trip.userID)
                return Content("Bạn không thể sửa bài của người khác");
            else return View(trip);
        }
        public ActionResult Moment(int id)
        {
            return View(data.BestMoments.Where(p => p.momentID == id).FirstOrDefault());
        }
        public ActionResult Moments()
        {
            var moments=data.BestMoments.OrderByDescending(p => p.Date_create).ToList<BestMoment>();
            List<List<BestMoment>> list = new List<List<BestMoment>>();
            for (int i = 0; i < moments.Count; i=i+3)
            {
                int j = i;
                List<BestMoment> tmp = new List<BestMoment>();
                while (((j - i) <= 2)&&(j<moments.Count))
                {
                    tmp.Add(moments[j]);
                    j++;
                }
                list.Add(tmp);
            }
            ViewBag.list = list;
            return View();

        }
        //-------------------------------------------
        [MyFirstBlog.Common.CustomAthorize(Roles="friends,admin,superadmin")]
        [HttpPost]
        public void Post(BestMoment newmoment)
        {
                var crnt_user = (MyFirstBlog.Models.user)Session["current_user"];
                var newpost = new BestMoment();
                newpost.Date_create = DateTime.Now;
                newpost.momentID = data.BestMoments.OrderByDescending(p=>p.momentID).FirstOrDefault().momentID+1;
                newpost.Title = newmoment.Title;
                newpost.Image = newmoment.Image;
                newpost.Summary = newmoment.Summary;
                newpost.userID=crnt_user.userID;
                data.BestMoments.Add(newpost);
                data.SaveChanges();
        }
    }
}

MyFirstBlog/Views/Admin/DailyPost.cshtml
@model IEnumerable<MyFirstBlog.Models.DailyPost>
<div class="Container">
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>Post ID</td>
                <td>Date</td>
                <td>Title</td>
                <td>Content</td>
                <td colspan="3">Action</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var post in Model)
            {
                <tr id="row-@post.postID">
                    <td>@post.postID</td>
                    <td>@post.dateWrite.ToString("MMMM dd,yyyy")</td>
                    <td>@post.postTitle</td>
                    <td><p style="width:200px;overflow:hidden;white-space:nowrap">@post.postContent</p></td>
                    <td><a class="btn btn-info"  href="/DailyPost/Post?id=@post.postID.ToString()" target="_blank">View</a></td>
                    <td><a class="btn btn-info" href="/DailyPost/EditPost?id=@post.postID.ToString()" target="_blank"><span class="btn-edit" data-id=@post.postID.ToString()>Edit</span></a></td>
                    <td><button class="btn-delete btn btn-danger" data-id=@post.postID.ToString()>Delete</button></td>
                </tr>
            }
        </tbody>
    </table>
</div>
    <script>
        $(function () {
            $(".btn-delete").click(function () {
                var postid=$(this).attr("data-id");
                if (confirm("You're gonna delete this post. Are you sure?"))
                {
                    $.ajax({
                        url: "/DailyPost/DeletePost",
                        type: "post",
                        data: { id: postid },
                        success: function (data) {
                            if (data == "succeed") {
                                $("#row-" + postid).remove();
                            }
                            else
                            {
                                alert(data);
                            }
                        }
                    })
                }
            })
        })
    </script>    

MyFirstBlog/Views/Admin/EditTrip.cshtml
@model MyFirstBlog.Models.Trip
@using MyFirstBlog.Models
<meta name="viewport" content="width=device-width" />
<title>Edit Trip</title>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href="http://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Noticia+Text:400,400italic,700,700italic" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<div class="Container" style="padding:20px;">
    <div>
        <h1>Chỉnh sửa bài viết</h1><br />
        @{
            user crnt_user = (user)Session["current_user"];
            <h4><mark>Người viết hiện tại: @crnt_user.username</mark></h4>
        }
        <mark>
            Nếu muốn thêm ảnh:<br />
            <span>
                Chú ý:<br />
                1, Không nên lấy ảnh từ facebook vì nó có thời gian timeout, nghĩa là ảnh đó không tồn tại mãi<br />
                2, Nếu lấy ảnh từ google photo thì phải để public cái ảnh hoặc cả folder ảnh<br />
                3, Upload lên <a href="https://www.flickr.com/" target="_blank">Flickr.com</a> hoặc <a href="http://imgur.com/" target="_blank">Imgur.com</a><br />
                Sau đó lấy link ảnh(URL) rồi điền vào chỗ thêm ảnh(Cách này tốt nhất)<br />
                4, Hình ảnh giữ nguyên tỉ lệ bằng cách chỉ điền width. lớn nhất 800px thôi nhé!
            </span>
        </mark>
    </div>
    @using (Html.BeginForm("Writetrip", "FriendsandMe", FormMethod.Post, new { id = "form" }))
    {
        <h4><label for="title">Tiêu đề bài viết</label></h4>
        <input id="title" name="title" class="form-control" value="@Model.postTitle" required />
        <h4><label for="summary">Tóm tắt bài viết</label></h4>
        <input id="summary" name="summary" value="@Model.postSummary" class="form-control" required />
        <h4><label for="thumbnail">Ảnh hiển thị(điền URL hình ảnh)</label></h4>
        <input id="thumbnail" name="thumbnail" class="form-control" value="@Model.imgThumbnail" required />
        <img class='img-thumbnail img-responsive' id="img-thumbnail" style='max-width:200px' src="@Model.imgThumbnail" />
        <h4><label for="thumbnail">Link Folder ảnh chia sẻ(nếu có)</label></h4>
        <input id="folder" name="folder" class="form-control" />
        <h4><label for="id=editor">Nội dung bài viết</label></h4>
        <textarea id="editor" name="editor"></textarea>

        <input id="text-content" name="content" value="@Model.postContent" hidden />
    }
    <a class="btn btn-primary" id="preview-btn" href="#preview-area">Xem thử</a>
    <input type="submit" class="btn btn-danger" form="form" id="btn-submit" value="Đăng bài" />
</div>
<div id="preview-area">
    <h2 style="border-bottom:0.5px solid black">Bài xem thử </h2>
    <h3><div id="title-preview"></div></h3>
    <div class="post-content">
        <div id="preview"></div>
    </div>
</div>
<script src="~/ckeditor/ckeditor.js"></script>
<script>

    $(function () {
            CKEDITOR.replace("editor");
            $("#preview-btn").click(function () {
                var html = CKEDITOR.instances.editor.getData();
                $("#title-preview").html($("#title").val());
                $("#text-content").val(html);
                $("#preview").html(html);

            })
            timer = setInterval(updateDiv, 100);
            function updateDiv() {
                var editorText = CKEDITOR.instances.editor.getData();
                $('#text-content').val(editorText);
            }
            $("#thumbnail").blur(function () {
                var src = $(this).val();
                $("#img-thumbnail").attr("src", src);
            })
            $(window).load(function () {
                var html = $("#text-content").val();
                CKEDITOR.instances.ckeditor1.setData(html);
            })
        })
</script>

MyFirstBlog/Views/Admin/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Admin Section</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Noticia+Text:400,400italic,700,700italic" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style>
        body {
            font-family: 'Montserrat', sans-serif !important;
        }

        #admin-area-left button {
            padding: 15px;
        }

        .actived {
            color: #fff;
            background-color: #286090;
            border-color: #204d74;
        }
        .navbar a{
            color:#fff !important;
        }
        .navbar{
            border:0px;
        }
    </style>
    <script>
        $(function () {
            $("#admin-area-left a.btn").click(function () {
                $("#admin-area-left a.btn").removeClass("active");
                $(this).addClass("active");
                var url = $(this).attr("data");
                $.ajax({
                    url: url,
                    type: "post",
                    success: function (data) {
                        $("#content").html(data);
                    }
                })
            });
            $("#admin-area-left button").click(function (){
                $("#admin-area-left button").removeClass("active");
                $(this).addClass("active");
            })
        })
    </script>
</head>
<body>
    <div id="Wrapper-admin" class="Container">
        <div id="admin-area-left" class="col-sm-2" style="background-color:rgb(28,125,208);height:100vh;overflow:auto;padding:0;">
            <button class="btn btn-primary" style="width:100%;"><h3 class="text-center">Khu vực quản trị</h3></button>
            <ul class="list-unstyled">
                <li>
                    <button class="btn btn-primary" style="width:100%;" data-toggle="collapse" data-target="#mypost">Khu vực riêng</button>
                    <ul class="list-unstyled collapse" id="mypost">
                        <li>
                            <a data="/Admin/DailyPost" class="btn btn-info" style="width:100%;">Danh sách bài viết</a>
                        </li>
                        <li>
                            <a data="/DailyPost/WritePost" class="btn btn-info" style="width:100%;">Viết bài mới</a>
                        </li>
                        <li>
                            <a data="/Admin/Trips" class="btn btn-info" style="width:100%;">Danh sách chuyến đi</a>
                        </li> 
                        <li>
                            <a data="/Admin/PendingTrips" class="btn btn-info" style="width:100%;">Bài viết chờ xác nhận</a>
                        </li>
                        <li>
                            <a data="/Admin/Users" class="btn btn-info" style="width:100%;">Quản lý tài khoản</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <button class="btn btn-primary" style="width:100%;" data-toggle="collapse" data-target="#mytrip">Bạn bè</button>
                    <ul class="list-unstyled collapse" id="mytrip">
                        <li>
                            <a data="/FriendsandMe/WriteTrip" class="btn btn-info" style="width:100%;">Viết bài các chuyến đi</a>
                        </li> 
                    </ul>
                </li>
            </ul>
        </div>
        <div id="admin-area-right" class="col-sm-10" style="overflow:scroll;height:100vh;padding:0;margin:0;">
            <div id="content">
            </div>
        </div>
    </div>
</body>
</html>

MyFirstBlog/Views/Admin/Login.cshtml
@model MyFirstBlog.Models.Security.UserLogin
<!doctype html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="~/Content/style_login.css" />
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <style>
        *{
            padding:0;
            margin:0;
        }
    </style>
</head>
<body>
    <div class="wrapper-dialog">
        <div class="wrapper-dialog-second"></div>
        <div id="dialog-login">
            <div id="switch-login-area">
                <div class="label-login" id="label-login" style="width:100%">Đăng Nhập Tài Khoản Admin</div>
            </div>
            <div id="content-login-area">
                <div id="content-login" class="dialog-login-content">
                    <div class="form-login">
                        @using (Html.BeginForm("Login", "Admin", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true)
                            <div class="editor-field">
                                @Html.TextBoxFor(model=>model.UserName, new { placeholder = "Tài khoản", id = "usernameLogin" })
                                @Html.ValidationMessageFor(model => model.UserName)
                            </div>
                            <div class="editor-field">
                                @Html.PasswordFor(model => model.Password, new { placeholder = "Mật khẩu", id = "passwordLogin" })
                                @Html.ValidationMessageFor(model => model.Password)
                            </div>
                            <div id="alertlogin"></div>
                            <div class="editor-field">
                                <br />
                                <input type="checkbox" name="rememberme" id="rememberme" />
                                Nhớ đăng nhập
                            </div>
                            <input type="submit" value="Login" id="login-pressed" />
                            <div><span style="color:red;font-size:20px;">@ViewBag.inform</span></div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>      
    <script>
        $(function () {
            $(window).load(function () {
            $(".wrapper-dialog").css("visibility", "visible");
            $("input").css({ "padding": "17px 0px" });
        })
            $("#login-pressed").click(function () {
                var userLogOn = JSON.stringify({
                    UserName: $("#usernameLogin").val(),
                    PassWord: $("#passwordLogin").val(),
                    RememberMe: $("#rememberme").is(":checked")
                });
                $.ajax({
                    url: "/Home/Login",
                    contentType: "application/json",
                    data: userLogOn,
                    dataType: "json",
                    type: "post",
                    success: function (response) {
                        if (response.boolean == true) {
                            window.location.href = "/admin";
                        }
                        else {
                            $("#alertlogin").html("<span style=\"color:red\" id=\"notif-login\">Password is incorrect</span>");
                        }
                    },
                    error: function (response) {
                        alert(response);
                    }
                });
            })
            $("#form-login :input").focus(function () {
                $("#notif-login").html("<div id=\"alertlogin\"></div>")
            })
        });
    </script>
</body>
</html>

MyFirstBlog/Views/Admin/PendingTrips.cshtml
@model IEnumerable<MyFirstBlog.Models.previewTrip>

<div class="Container">
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <td>Mã bài viết</td>
                    <td>Ngày viết</td>
                    <td>Tên bài viết</td>
                    <td>Người viết</td>
                    <td colspan="2"></td>
                </tr>
            </thead>
            <tbody>
                @foreach (var post in Model)
                {
                    <tr id="row-@post.previewID">
                        <td>@post.previewID</td>
                        <td>@post.date.Value.ToString("MMMM dd,yyyy")</td>
                        <td>@post.postTitle</td>
                        <td>@MyFirstBlog.Common.Methods.findusernameByID((int)post.userID)</td>
                        <td>
                            <a class="btn btn-primary" href="/FriendsandMe/PreviewTrip?id=@post.previewID" target="_blank">Xem</a>
                        </td>
                        <td>
                            <a class="delete btn btn-danger" data-id="@post.previewID">Xóa</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<script>
        $(function () {
            $(".delete").click(function () {
                var postid=$(this).attr("data-id");
                if (confirm("You're gonna delete this article. Are you sure?"))
                {
                    $.ajax({
                        url: "/Admin/DeletePendingTrip",
                        type: "post",
                        data: { id: postid },
                        success: function () {
                                $("#row-" + postid).remove();
                        },
                        error: function (data) {
                            alert(data);
                        }
                        
                    })
                }
            })
        })
</script>    

MyFirstBlog/Views/Admin/Trips.cshtml
@model IEnumerable<MyFirstBlog.Models.Trip>


<div class="Container">
    <h2>Danh sách các bài viết chuyến đi</h2>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <td>Mã</td>
                    <td>Tên</td>
                    <td>Ngày viết</td>
                    <td>Người viết</td>
                    <td>Tóm tắt</td>
                    <td colspan="3"></td>
                </tr>
            </thead>
            <tbody>
                @foreach (var trip in Model)
                {
                    <tr id="row-@trip.postID">
                        <td>@trip.postID</td>
                        <td>@trip.postTitle</td>
                        <td>@trip.date.Value.ToString("MMMM dd,yyyy")</td>
                        <td>@MyFirstBlog.Common.Methods.findusernameByID((int)trip.userID)</td>
                        <td>@trip.postSummary</td>
                        <td>
                            <a class="btn btn-primary" href="/FriendsandMe/Trip?id=@trip.postID" target="_blank">Xem</a>
                        </td>
                        <td>
                            <a class="edit btn btn-primary" href="/FriendsandMe/EditTrip?id=@trip.postID" target="_blank">Sửa</a>
                        </td>
                        <td>
                            <a class="delete btn btn-danger" data-id="@trip.postID">Xóa</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<script>
    $(function () {
        $(".delete").click(function () {
            var postid = $(this).attr("data-id");
            if (confirm("You're gonna delete this article. Are you sure?")) {
                $.ajax({
                    url: "/Admin/DeleteTrip",
                    type: "post",
                    data: { id: postid },
                    success: function (data) {
                            $("#row-" + postid).remove();
                    }
                })
            }
        })
    })
</script>    